### ISSUE TITLE
Ideas from Bristol Wagtail Accessibility Sprint (Jan 2020)

### ISSUE THREAD

**Issue by tomdyson** [takeflight/wagtail-accessibility#11]
- What are the alternatives to tota11y that we could include in this plug-in?
    - [Axe-core](https://github.com/dequelabs/axe-core) is comprehensive, open source and up to date. But it’s a low-level API, exposed to the commercial (currently free) browser plug-ins.
        - There’s an open source [Wordpress plugin](https://github.com/OIT-Design/ncsu-a11y-helper) for axe-core which is designed for content creators and looks roughly equivalent to the tota11y UI - see [slides](https://docs.google.com/presentation/d/e/2PACX-1vROBCmDyBQI2Zez1hoVBSV1rUp_9Xad6K2J3-KDEr0IbewMqbKePoSwgicLpIHIgnw9v9cgwNu7furx/pub?start=false&loop=false&delayms=3000#slide=id.g2fbab35998_0_62)
        - axe-core is highly configurable - we could enable specific rules and checks based on user type, for example. We can easily output errors to the browser console but we’d need to build the UI ourselves.
    - https://tenon.io/ is apparently popular and well-respected, but I couldn’t get it to work. It’s a commercial server-side API - you `POST` a URL or a chunk of HTML to it.
    - [WAVE](https://wave.webaim.org/) is a popular web-based tool for identifying accessibility and Web Content Accessibility Guideline errors. It’s free for single page use - e.g. https://wave.webaim.org/report#/https://wagtail.io - but it’s not obvious how to check non-public pages.
    - [Siteimprove](https://siteimprove.com/) is a commercial service which includes accessibility reporting. It provides integrations with [several popular CMSs](https://siteimprove.com/en-gb/core-platform/integrations/cms-plugin/). [Youtube demo of Drupal integration](https://www.youtube.com/watch?v=n9kouBNmOAw&t=8).
- How could we make wagtail-accessibility better?
    - is https://github.com/Khan/tota11y/ up to date in wagtail-accessibility? yes #8 
    - Are there any options for tota11y that we could make configurable? no
    - We could make the visibility of `wagtail-accessibility` configurable, based on user group (#10)
    - We could create a UI for `axe-core` violation reports (hard)
    - We could enable `axe-core` and output violations to the console (easy):
```html
<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/vue-axe"></script>
<script>Vue.use(VueAxe, { config: {} })</script>
```

**Comment by thibaudcolas** [comment]
Years later, here we are :) [Introducing Wagtail’s new accessibility checker](https://wagtail.org/blog/introducing-wagtails-new-accessibility-checker/). And future plans: [Looking for sponsorship – Accessibility checks for site administrators](https://wagtail.org/blog/looking-for-sponsorship-accessibility-checks-for-site-administrators/).

wagtail-accessibility still provides a lot of value as it has a very different feature set from what we ended up building directly in Wagtail
